[build]
  base = "apps/web"
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--prefix=apps/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
