// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sportsmvp-landing/InsideEdge.tsx": () => import("../components/mockups/sportsmvp-landing/InsideEdge.tsx"),
  "./components/mockups/sportsmvp-landing/MathNotMystique.tsx": () => import("../components/mockups/sportsmvp-landing/MathNotMystique.tsx"),
  "./components/mockups/sportsmvp-landing/PayForWins.tsx": () => import("../components/mockups/sportsmvp-landing/PayForWins.tsx")
};
